### ISSUE TITLE
LiveHelpNow SDk hacked with CoinHive

### ISSUE THREAD

**Issue by dougsillars** [shayanb/inse6630#4]
https://www.bleepingcomputer.com/news/security/cryptojacking-script-found-in-live-help-widget-impacts-around-1-500-sites/

Incident report from LiveHelpNow: https://blog.livehelpnow.net/security-incident-nov-23rd-2017/

**Comment by tmursch** [comment]
Twitter Moment of this incident includes screenshots, analysis, etc.

Cryptojacking campaign using @LiveHelpNow's chat widget
https://twitter.com/i/moments/933846985601191936

**Comment by shayanb** [comment]
referenced here: https://github.com/shayanb/inse6630/commit/d22a9d515669178497c0d84dba3d2fb304cc6ea6

Maybe there'd be a need of additional analysis later on but for now there are too much details to include all the incidents in detail.
